name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
      with:
        java-version: 8
        distribution: adopt
    - uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - run: sbt -v "+ Test/compile"
