name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: olafurpg/setup-scala@v13
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v6
    - run: sbt -v "+ test:compile"
