name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
      with:
        java-version: 8
        distribution: adopt
    - uses: coursier/cache-action@v6
    - run: sbt -v "+ Test/compile"
