name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 9 * * 4'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v5
    - run: sbt -v "+ test:compile"
