name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        java-version: 8
        distribution: adopt
    - uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - run: sbt -v "+ Test/compile"
